# Generated by Django 5.1.3 on 2024-11-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieshots',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
