# Generated by Django 5.1.3 on 2024-11-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_rating_ip_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.SmallIntegerField(default=0, verbose_name='Звезда'),
        ),
    ]
