# Generated by Django 5.1.3 on 2024-11-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_rating_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.FloatField(default=3.5, verbose_name='Рейтинг фильма'),
        ),
    ]
