# Generated by Django 5.1.3 on 2024-12-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_favourites_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movies.movie'),
        ),
    ]
